//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMPowerHour
    {
        public short StoreNumber { get; set; }
        public string StoreName { get; set; }
        public int Week { get; set; }
        public short Days { get; set; }
        public string WeekType { get; set; }
        public System.TimeSpan Hour { get; set; }
        public float Trade { get; set; }
        public short Rank { get; set; }
        public int Working { get; set; }
        public int Holiday { get; set; }
    }
}
