//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayPlanningEmp
    {
        public int EntryId { get; set; }
        public int StoreNumber { get; set; }
        public string PersonNum { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> Taken { get; set; }
        public Nullable<int> Scheduled { get; set; }
        public Nullable<int> YearStart { get; set; }
    }
}
