//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KronosEmployeeSummary
    {
        public Nullable<short> HomeBranch { get; set; }
        public Nullable<short> Region { get; set; }
        public string Division { get; set; }
        public string Channel { get; set; }
        public string PersonNumber { get; set; }
        public Nullable<decimal> EmployeeStandardHours { get; set; }
        public Nullable<System.DateTime> SignedOffThrough { get; set; }
        public string JobRole { get; set; }
        public string PersonName { get; set; }
        public bool KronosUser { get; set; }
        public string BranchName { get; set; }
        public bool Scheduled { get; set; }
        public Nullable<byte> ReportingRoleFlag { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
