//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveVacanciesToCancel
    {
        public int EntryId { get; set; }
        public int JobReqId { get; set; }
        public string RaisedBy { get; set; }
        public System.DateTime RaisedDate { get; set; }
        public bool Completed { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    }
}
