//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeakData
    {
        public int StoreNumber { get; set; }
        public int WeekNumber { get; set; }
        public Nullable<double> Budget { get; set; }
        public Nullable<double> Contract { get; set; }
        public Nullable<double> Holiday { get; set; }
        public Nullable<byte> Temps { get; set; }
        public Nullable<byte> TempsOption { get; set; }
    }
}
