//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerHoursProfile
    {
        public int EntryID { get; set; }
        public Nullable<short> Store { get; set; }
        public string Store_Name { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<short> Days { get; set; }
        public string Territory { get; set; }
        public string Week_Type { get; set; }
        public Nullable<float> C00_TP { get; set; }
        public Nullable<float> C01_TP { get; set; }
        public Nullable<float> C02_TP { get; set; }
        public Nullable<float> C03_TP { get; set; }
        public Nullable<float> C04_TP { get; set; }
        public Nullable<float> C05_TP { get; set; }
        public Nullable<float> C06_TP { get; set; }
        public Nullable<float> C07_TP { get; set; }
        public Nullable<float> C08_TP { get; set; }
        public Nullable<float> C09_TP { get; set; }
        public Nullable<float> C10_TP { get; set; }
        public Nullable<float> C11_TP { get; set; }
        public Nullable<float> C12_TP { get; set; }
        public Nullable<float> C13_TP { get; set; }
        public Nullable<float> C14_TP { get; set; }
        public Nullable<float> C15_TP { get; set; }
        public Nullable<float> C16_TP { get; set; }
        public Nullable<float> C17_TP { get; set; }
        public Nullable<float> C18_TP { get; set; }
        public Nullable<float> C19_TP { get; set; }
        public Nullable<float> C20_TP { get; set; }
        public Nullable<float> C21_TP { get; set; }
        public Nullable<float> C22_TP { get; set; }
        public Nullable<float> C23_TP { get; set; }
    }
}
