//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFTPCaseAudit
    {
        public int ActionID { get; set; }
        public int CaseID { get; set; }
        public string ActionType { get; set; }
        public string Comment { get; set; }
        public string CompletedBy { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
    
        public virtual RFTPCaseStub RFTPCaseStub { get; set; }
    }
}
