//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACheckAnswer
    {
        public int CheckAnswerID { get; set; }
        public int CheckID { get; set; }
        public string Text { get; set; }
        public bool Correct { get; set; }
    
        public virtual SACheck SACheck { get; set; }
    }
}
