//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortShift
    {
        public int WeekNumber { get; set; }
        public int HomeStore { get; set; }
        public string PersonNum { get; set; }
        public string PersonName { get; set; }
        public System.DateTime PunchDate { get; set; }
    }
}
