//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreReference
    {
        public short Br_ { get; set; }
        public string UK_BR { get; set; }
        public string Store_Name { get; set; }
        public string Division { get; set; }
        public Nullable<short> Region { get; set; }
        public string Region_name { get; set; }
        public string Channel { get; set; }
    }
}
