//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempRegionLookup
    {
        public int EntryId { get; set; }
        public Nullable<short> Area { get; set; }
        public Nullable<short> Store { get; set; }
    }
}
