//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAudit
    {
        public int EntryId { get; set; }
        public int TicketId { get; set; }
        public string Action { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string User { get; set; }
    
        public virtual TicketStub TicketStub { get; set; }
    }
}
