//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketTemplate()
        {
            this.TicketAnswers = new HashSet<TicketAnswer>();
        }
    
        public int QuestionId { get; set; }
        public int TicketTypeId { get; set; }
        public string Question { get; set; }
        public string ReturnType { get; set; }
        public Nullable<byte> GrpLimit { get; set; }
        public string apiIdent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketAnswer> TicketAnswers { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
