//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnknownIpLog
    {
        public int EntryId { get; set; }
        public int storeNumber { get; set; }
        public string IpRange { get; set; }
        public System.DateTime DateTimeAdded { get; set; }
        public Nullable<bool> Reviewed { get; set; }
    }
}
