//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int EntryId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string EmpNum { get; set; }
        public Nullable<byte> AccessLvl { get; set; }
        public Nullable<byte> AreaLevel { get; set; }
        public string IP { get; set; }
        public string Domain { get; set; }
    }
}
