//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessArea
    {
        public int EntryID { get; set; }
        public string UserName { get; set; }
        public string AreaName { get; set; }
    
        public virtual UserAccess UserAccess { get; set; }
    }
}
