//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyPosition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VacancyPosition()
        {
            this.VacancyRequests = new HashSet<VacancyRequest>();
            this.vw_VacancyRequestsAdmin = new HashSet<vw_VacancyRequestsAdmin>();
        }
    
        public short PositionId { get; set; }
        public string FriendlyName { get; set; }
        public string SFName { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public Nullable<decimal> RateOfPay { get; set; }
        public Nullable<short> SFPositionId { get; set; }
        public string Chain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacancyRequest> VacancyRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vw_VacancyRequestsAdmin> vw_VacancyRequestsAdmin { get; set; }
    }
}
