//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VacancyRequest()
        {
            this.RequestComments = new HashSet<RequestComment>();
        }
    
        public int EntryId { get; set; }
        public Nullable<int> SFRefNo { get; set; }
        public short PositionCode { get; set; }
        public short Heads { get; set; }
        public short ContractHrs { get; set; }
        public bool Approved { get; set; }
        public bool Rejected { get; set; }
        public string RaisedBy { get; set; }
        public System.DateTime RaisedDate { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public bool Replace { get; set; }
        public bool Repost { get; set; }
        public bool Internal { get; set; }
        public Nullable<bool> Emailed { get; set; }
        public short StoreNumber { get; set; }
        public bool Show { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestComment> RequestComments { get; set; }
        public virtual VacancyPosition VacancyPosition { get; set; }
    }
}
