//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AvailabilitySummary
    {
        public Nullable<short> HomeBranch { get; set; }
        public byte DayNum { get; set; }
        public Nullable<int> C08_AV { get; set; }
        public Nullable<int> C09_AV { get; set; }
        public Nullable<int> C10_AV { get; set; }
        public Nullable<int> C11_AV { get; set; }
        public Nullable<int> C12_AV { get; set; }
        public Nullable<int> C13_AV { get; set; }
        public Nullable<int> C14_AV { get; set; }
        public Nullable<int> C15_AV { get; set; }
        public Nullable<int> C16_AV { get; set; }
        public Nullable<int> C17_AV { get; set; }
        public Nullable<int> C18_AV { get; set; }
        public Nullable<int> C19_AV { get; set; }
        public Nullable<int> C20_AV { get; set; }
        public Nullable<int> C21_AV { get; set; }
        public Nullable<int> C22_AV { get; set; }
        public Nullable<int> C23_AV { get; set; }
    }
}
