//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AvailabilityPattern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vw_AvailabilityPattern()
        {
            this.AvailabilityDays = new HashSet<AvailabilityDay>();
        }
    
        public int PatternId { get; set; }
        public Nullable<short> HomeBranch { get; set; }
        public string PersonNumber { get; set; }
        public string PersonName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastConfirmedDate { get; set; }
        public string LastConfirmedBy { get; set; }
        public int PatternType { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailabilityDay> AvailabilityDays { get; set; }
    }
}
