//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActionPlan
    {
        public long RowId { get; set; }
        public int EntryId { get; set; }
        public System.DateTime DateTimeSubmitted { get; set; }
        public string Text { get; set; }
    }
}
