//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CPCWSchedules
    {
        public long RowId { get; set; }
        public Nullable<int> CST_CNTR_INT { get; set; }
        public string BRANCH { get; set; }
        public Nullable<int> FNCL_WK { get; set; }
        public string FORENAMES { get; set; }
        public string SURNAME { get; set; }
        public string D1_START { get; set; }
        public string D1_END { get; set; }
        public string D2_START { get; set; }
        public string D2_END { get; set; }
        public string D3_START { get; set; }
        public string D3_END { get; set; }
        public string D4_START { get; set; }
        public string D4_END { get; set; }
        public string D5_START { get; set; }
        public string D5_END { get; set; }
        public string D6_START { get; set; }
        public string D6_END { get; set; }
        public string D7_START { get; set; }
        public string D7_END { get; set; }
        public string TASKDESC { get; set; }
    }
}
