//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ContractBaseDetail
    {
        public string Chain { get; set; }
        public string Division { get; set; }
        public short Region { get; set; }
        public string StoreName { get; set; }
        public short StoreNumber { get; set; }
        public Nullable<short> Contract_Base { get; set; }
        public Nullable<double> Contract_Hours { get; set; }
        public Nullable<short> Highest_Week { get; set; }
        public Nullable<short> Lowest_Week { get; set; }
        public Nullable<decimal> P1 { get; set; }
        public Nullable<decimal> P2 { get; set; }
        public Nullable<decimal> P3 { get; set; }
        public Nullable<decimal> P4 { get; set; }
        public Nullable<decimal> P5 { get; set; }
        public Nullable<decimal> P6 { get; set; }
        public Nullable<decimal> P7 { get; set; }
        public Nullable<decimal> P8 { get; set; }
        public Nullable<decimal> P9 { get; set; }
        public Nullable<decimal> P10 { get; set; }
        public Nullable<decimal> P11 { get; set; }
        public Nullable<decimal> P12 { get; set; }
        public int TotalHoliday { get; set; }
    }
}
