//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FootfallHourly
    {
        public string Key { get; set; }
        public string Year { get; set; }
        public Nullable<short> WeekNumber { get; set; }
        public string Day { get; set; }
        public Nullable<short> Hour_In_Day_24 { get; set; }
        public string Chain { get; set; }
        public string Division { get; set; }
        public short Region { get; set; }
        public short StoreNumber { get; set; }
        public string StoreName { get; set; }
        public Nullable<short> Footfall_Volume { get; set; }
    }
}
