//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GmWeWorking
    {
        public long RowId { get; set; }
        public string Chain { get; set; }
        public string Division { get; set; }
        public Nullable<short> Region { get; set; }
        public Nullable<short> StoreNumber { get; set; }
        public string StoreName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<byte> day { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Worked { get; set; }
        public Nullable<int> Holiday { get; set; }
        public Nullable<int> NotPunched { get; set; }
        public Nullable<int> Closed { get; set; }
    }
}
