//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Last12MonthRFTPCases
    {
        public int CaseID { get; set; }
        public string PersonNumber { get; set; }
        public short StoreNumber { get; set; }
        public byte Stage { get; set; }
        public bool Override { get; set; }
        public bool Reassign { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public bool Confirmed { get; set; }
        public bool Completed { get; set; }
        public string Year { get; set; }
        public Nullable<byte> Period { get; set; }
        public bool Show { get; set; }
    }
}
