//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PilotDailyUnders
    {
        public int WeekNumber { get; set; }
        public Nullable<short> StoreNumber { get; set; }
        public Nullable<double> TotalUnders { get; set; }
    }
}
