//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RFTP_Notifications
    {
        public short Region { get; set; }
        public int Confirms { get; set; }
        public int Outstanding { get; set; }
        public int SAOverdue { get; set; }
        public string Username { get; set; }
    }
}
