//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StoreLocations
    {
        public string Chain { get; set; }
        public string Division { get; set; }
        public short Region { get; set; }
        public short StoreNumber { get; set; }
        public string StoreName { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public int MinervaStore { get; set; }
        public int MinervaTransferStore { get; set; }
        public Nullable<short> Contract_Base { get; set; }
        public Nullable<double> Contract_Hours { get; set; }
        public Nullable<byte> StoreBand { get; set; }
        public Nullable<decimal> TotalTradeTransfer { get; set; }
        public string TradeTransfer { get; set; }
    }
}
