//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SFOpenVacancies
    {
        public int EntryId { get; set; }
        public int JobReqId { get; set; }
        public string PositionNumber { get; set; }
        public string Company { get; set; }
        public string BusinessUnit { get; set; }
        public short StoreNumber { get; set; }
        public short JobCode { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public short TotalVacantHours { get; set; }
        public short Headcount { get; set; }
        public string Chain { get; set; }
    }
}
