//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StoreDeploymentDashTrend
    {
        public string Chain { get; set; }
        public string Division { get; set; }
        public short Region { get; set; }
        public short StoreNumber { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> PlanningAhead { get; set; }
        public Nullable<int> Recruitment { get; set; }
        public Nullable<int> Absence { get; set; }
        public Nullable<int> GMWorking { get; set; }
        public Nullable<int> WeekCount { get; set; }
    }
}
