//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StoreDeploymentDash
    {
        public string Chain { get; set; }
        public string Division { get; set; }
        public short Region { get; set; }
        public short StoreNumber { get; set; }
        public string StoreName { get; set; }
        public string Year { get; set; }
        public Nullable<byte> Period { get; set; }
        public int WeekNumber { get; set; }
        public string PlanningAhead { get; set; }
        public string Recruitment { get; set; }
        public string Absence { get; set; }
        public string GMWorking { get; set; }
    }
}
