//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ScheduleData
    {
        public int EntryId { get; set; }
        public string Chain { get; set; }
        public string Division { get; set; }
        public short Region { get; set; }
        public short StoreNumber { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> PersonNumber { get; set; }
        public Nullable<decimal> ContractHours { get; set; }
        public string FullName { get; set; }
        public string ShiftType { get; set; }
        public string TransferBranch { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<byte> DayNum { get; set; }
        public Nullable<decimal> PersonWeekTotal { get; set; }
        public Nullable<decimal> DayWeekTotal { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public Nullable<short> JobCode { get; set; }
    }
}
