//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TradingHoursForAvlblty
    {
        public int StoreNumber { get; set; }
        public Nullable<int> SundayOpen { get; set; }
        public Nullable<int> SundayClose { get; set; }
        public Nullable<int> MondayOpen { get; set; }
        public Nullable<int> MondayClose { get; set; }
        public Nullable<int> TuesdayOpen { get; set; }
        public Nullable<int> TuesdayClose { get; set; }
        public Nullable<int> WednesdayOpen { get; set; }
        public Nullable<int> WednesdayClose { get; set; }
        public Nullable<int> ThursdayOpen { get; set; }
        public Nullable<int> ThursdayClose { get; set; }
        public Nullable<int> FridayOpen { get; set; }
        public Nullable<int> FridayClose { get; set; }
        public Nullable<int> SaturdayOpen { get; set; }
        public Nullable<int> SaturdayClose { get; set; }
    }
}
