//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Top100CreditSummary
    {
        public int EntryID { get; set; }
        public int WeekNumber { get; set; }
        public string Division { get; set; }
        public short Region { get; set; }
        public short StoreNumber { get; set; }
        public string StoreName { get; set; }
        public Nullable<double> SundayReq { get; set; }
        public Nullable<double> SaturdayReq { get; set; }
        public decimal SundayDeployed { get; set; }
        public decimal SaturdayDeployed { get; set; }
        public Nullable<double> SundayCredit { get; set; }
        public Nullable<double> SaturdayCredit { get; set; }
        public short SundayAvailable { get; set; }
        public short SaturdayAvailable { get; set; }
        public string SundayRAG { get; set; }
        public string SaturdayRAG { get; set; }
        public string TotalRAG { get; set; }
        public Nullable<double> FinalTarget { get; set; }
        public Nullable<double> SOH { get; set; }
    }
}
