//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aion.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WfmContext : DbContext
    {
        public WfmContext()
            : base("name=WfmContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Store> Stores { get; set; }
    
        public virtual ObjectResult<sp_GetBranchMenu_Result> sp_GetBranchMenu(Nullable<byte> lvl, string area)
        {
            var lvlParameter = lvl.HasValue ?
                new ObjectParameter("lvl", lvl) :
                new ObjectParameter("lvl", typeof(byte));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBranchMenu_Result>("sp_GetBranchMenu", lvlParameter, areaParameter);
        }
    }
}
